### ISSUE TITLE
Exception with undefined waypoint components from C++

### ISSUE THREAD

**Issue by bbbcode** [AIS-Bonn/TopiCo#1]
Hi! 

I'm having some issues generating multi-point trajectories with unconstrained velocities and accelerations at intermediate waypoints. When setting those to NaNs I get the following:

> Domain error. To compute complex results from real x, use 'sqrt(complex(x))'.
> Error in error (line 19)
> Aborted

[Here's a link](https://gist.github.com/bbbcode/44e6639e7752a07049c6562d33b8a378) to a modified version of main.cpp that demonstrates the issue. In it I'm moving axis 0 to positions [5, 4, 3], with velocities [0, NaN, 0] and accelerations [0, NaN, 0].

**Comment by MariusBeul** [comment]
Hi bbbcode,
thanks for reporting this Bug. I can confirm it on my machine. I pushed a Bugfix for the MATLAB (plain and mexa64) version. Feel free to use the generate_code.m to generate updated c files. I will need some time to update the cpp version in the repo since I want to switch the ROS node from the static library to including the cpp sources...

Best,
Marius
