### ISSUE TITLE
Large position overshoot at intermidiate waypoints

### ISSUE THREAD

**Issue by yakunsjtu** [AIS-Bonn/TopiCo#17]
Hi developers, I tried to use this package for trajectory planning including more than 2 waypoints, but an overshoot occurred at the intermediate waypoint.

Here is my script:

```
clearvars;
close all;
addpath(genpath(pwd));


State_start       = [ 20.0,  0.0,  0.0;
                      -15.0,  0.0,  0.0;
                      100.0,  0.0,  0.0];
% wayPt1                  
Waypoints(:,:,1)  = [ 20.0,  0.0,  0.0,  0.0,  0.0;
                      -15.0,  0.0,  0.0,  0.0,  0.0;
                      100.0,  0.0,  0.0,  0.0,  0.0];

% wayPt2
Waypoints(:,:,2)  = [ 20.0,  0.0,  0.0,   0.0,  0.0;
                      0.0,  NaN,  NaN,    0.0,  0.0;
                      100.0,  NaN,  NaN,  0.0,  0.0];
% wayPt3                  
Waypoints(:,:,3)  = [ 12.0,  0.0,  0.0,  0.0,  0.0;
                      9.0,   0.0,  0.0,  0.0,  0.0;
                      95.0,  0.0,  0.0,  0.0,  0.0];
                  

onesN = ones(1, 3);

VxMax = 45.0;
VyMax = 50.0;
VtMax = 7.5;

AxMax = 5.0;
AyMax = 10.0;
AtMax = 1.5;

JxMax = 5.0;
JyMax = 5.0;
JtMax = 5.0;

V_max             = [ onesN * VxMax;
                      onesN * VyMax;
                      onesN * VtMax];
V_min             = -V_max;
A_max             = [ onesN * AxMax;
                      onesN * AyMax;
                      onesN * AtMax];
A_min             = -A_max;
J_max             = [ onesN * JxMax;
                      onesN * JyMax;
                      onesN * JtMax];
J_min             = -J_max;
A_global          = [ 0.0;
                      0.0;
                      0.0];
     

num_axes          = size(Waypoints,1);
num_waypoints     = size(Waypoints,3);
b_sync_V          = true(num_axes,num_waypoints);
b_sync_A          = true(num_axes,num_waypoints);
b_sync_J          = false(num_axes,num_waypoints);
b_sync_W          = false(num_axes,num_waypoints);
b_rotate          = false(num_axes-1,num_waypoints);
b_hard_V_lim      = false(num_axes,num_waypoints);
b_catch_up        = true(num_axes,num_waypoints);
direction         = zeros(num_axes,num_waypoints,'int8');
ts_rollout        = 0.01;


%% ----------   Compute    ----------
tic;
[J_setp_struct,solution_out,T_waypoints,P,V,A,J,t] = topico(State_start,Waypoints,V_max,V_min,A_max,A_min,J_max,J_min,A_global,b_sync_V,b_sync_A,b_sync_J,b_sync_W,b_rotate,b_hard_V_lim,b_catch_up,direction,ts_rollout);
%[J_setp_struct,solution_out,T_waypoints,P,V,A,J,t] = topico_mex(State_start,Waypoints,V_max,V_min,A_max,A_min,J_max,J_min,A_global,b_sync_V,b_sync_A,b_sync_J,b_sync_W,b_rotate,b_hard_V_lim,b_catch_up,direction,ts_rollout);
t_elapsed = toc;


%% ----------     Output     ----------
disp(['Debug: Generated trajectory for ',int2str(num_axes),' axes and ',int2str(num_waypoints),' waypoints in ',num2str(t_elapsed),'s!']);
show_trajectory_1D;
```
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/28284575/167375156-f82eb406-4b59-42da-8dab-0debe8f1e6c8.png">

From the figure, the position of the second axis has a large overshoot (at T = 23, Y = 109). Did I mistaken something in the code? 

Thanks!

**Comment by MariusBeul** [comment]
Hi yakunsjtu,

thanks for using TopiCo!
You did not define Velocity and Acceleration of the second (red) axis. Thus, the algorithm finds the time-optimal trajectory from your initial conditions (P=-15) to the target position (P=0). Since the velocity in the waypoint is not defined, time-optimality means that the algorithm fully accelerates in the direction of the waypoint. This provokes the large overshoot after the waypoint.
Trajectories generated with TopiCo are "forward time-optimal", meaning every waypoint is optimally connected with the following, but TopiCo does _not_ look beyond the next waypoint. For a globally optimal trajectory, you could think about sampling based-approaches in combination with TopiCo like https://arxiv.org/abs/2205.02202 or analytical approaches like
https://www.ais.uni-bonn.de/papers/IROS_2019_Beul.pdf

Best regards
Marius

**Comment by yakunsjtu** [comment]
> 
Thank you MariusBeul!

In the README, it says
```
TopiCo has been successfully used as model predictive controller on different micro aerial vehicles
```
So I was thinking TopiCo acts as an MPC controller, it looks ahead several waypoints and outputs the optimal solution for the whole horizon. And we can take the first waypoint solution. And then we slide the window, start from the optimized state, looks ahead the following waypoints and optimize again...  But it seems TopiCo just consider the adjacent waypoint?

In some scenarios, the high level planner just provide some future waypoints without velocities, and the user may find it not easy to define velocities at the waypoints.  Maybe it would be helpful if the algorithm could make some clever prediction on the velocity to get a near globally optimal trajectory (at least we can have the option).

I'm wondering if the IROS paper can handle multiple waypoints with just waypoints not velocities provided. And do you have any code snippet for the IROS paper?

Thanks!

**Comment by MariusBeul** [comment]
In its current form, TopiCo only looks ahead to the next waypoint. However, due to the fast runtime it can be used in a hierarchy of planners to find globally optimum trajectories. The higher-level planner must provide velocities (or even acceleration) in all waypoints and you can use TopiCo to find the time-optimal trajectory from the current robot state (which might slightly deviate from the planned global path) to the next waypoint. For a global planner that incorporates velocities, you could also have a look at STOMP/CHOMP style planners (e.g. https://www.ais.uni-bonn.de/papers/ICRA_2019_Nieuwenhuisen.pdf).
Unfortunately, I can't provide the sources for the IROS paper. Sorry!

**Comment by yakunsjtu** [comment]
> In its current form, TopiCo only looks ahead to the next waypoint. However, due to the fast runtime it can be used in a hierarchy of planners to find globally optimum trajectories. The higher-level planner must provide velocities (or even acceleration) in all waypoints and you can use TopiCo to find the time-optimal trajectory from the current robot state (which might slightly deviate from the planned global path) to the next waypoint. For a global planner that incorporates velocities, you could also have a look at STOMP/CHOMP style planners (e.g. https://www.ais.uni-bonn.de/papers/ICRA_2019_Nieuwenhuisen.pdf). Unfortunately, I can't provide the sources for the IROS paper. Sorry!
Hi MariusBeul,
Thanks for providing these useful papers, I will take a look.
