### ISSUE TITLE
Large trajectory with NaN in waypoints

### ISSUE THREAD

**Issue by wilsonz91** [AIS-Bonn/TopiCo#3]
Hi, 

Thanks for contributing this package. I'm encountering large trajectories for a simple trajectory where the intermediate waypoint velocities/accelerations are set to NaN. Attached is the result. The set up in matlab is similar to your example 4 with only the following changes: 
```
State_start       = [ 0.0,  0.0,  0.0;
                      0.0,  0.0,  0.0;
                      0.0,  0.0,  0.0];
Waypoints(:,:,1)  = [ 1.0,  NaN,  NaN,  0.0,  0.0;
                      1.0,  NaN,  NaN,  0.0,  0.0;
                      0.0,  NaN,  NaN,  0.0,  0.0];
Waypoints(:,:,2)  = [ 2.0,  0.0,  0.0,  0.0,  0.0;
                      0.0,  0.0,  0.0,  0.0,  0.0;
                      0.0, -0.0,  0.0,  0.0,  0.0];
```
I set the intermediate velocities/accelerations to NaN since it does not need to be enforced. Could you please advise if I'm doing something wrong with the use of NaN? 

![trajectory](https://user-images.githubusercontent.com/25768686/114184138-61090280-993c-11eb-9bae-369f95ffe477.png)

**Comment by MariusBeul** [comment]
Hello wilsonz91,
thank you for reporting the issue and providing the example. When you set waypoint velocity and acceleration to NaN, the trajectory to this waypoint is time-optimal. Thus, there will be a large velocity when passing the first waypoint (nearly V_max in your case). After passing the waypoint, the velocity has to be reduced which due to the limited acceleration provokes this overshoot.
The method does _not_ optimize the entire trajectory with NaN degree of freedom, but only the segment that leads to the underdefined waypoint.

**Comment by wilsonz91** [comment]
Hello Marius,

Thank you for your prompt reply, I understand now. Could I follow up by asking how would you determine intermediate velocities/accelerations?

**Comment by MariusBeul** [comment]
Do I understand correctly that you want to optimize the intermediate velocities and accelerations to minimize the total trajectory time? If so, please have a look here for an idea: http://ais.uni-bonn.de/papers/IROS_2019_Beul.pdf
We sample multiple velocities and fit a polynomial to guess the global optimum.
